# Generated by Django 2.1.7 on 2019-03-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principal_investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_Dept', models.CharField(max_length=100)),
                ('P_designation', models.CharField(max_length=100)),
            ],
        ),
    ]
