# Generated by Django 2.1.7 on 2019-03-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_principal_investigator_principal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Co_name', models.CharField(max_length=100)),
                ('Co_designation', models.CharField(max_length=100)),
                ('Co_contact_no', models.CharField(max_length=20)),
                ('Co_email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
