# Generated by Django 2.1.7 on 2019-03-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190301_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_details',
            name='appr_date_erb',
            field=models.DateField(null=True),
        ),
    ]
